
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Label labInfo;
	
	private global::Gtk.ComboBox combSites;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.HBox hbox2;
	
	private global::Gtk.Label labUserName;
	
	private global::Gtk.Entry txtUserName;
	
	private global::Gtk.HBox hbox3;
	
	private global::Gtk.Label labPassword;
	
	private global::Gtk.Entry txtPassword;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.Alignment alignment1;
	
	private global::Gtk.Label labFull;
	
	private global::Gtk.Button btnLogin;
	
	private global::Gtk.Button btnReset;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView txtResult;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Login Test Tool");
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.labInfo = new global::Gtk.Label ();
		this.labInfo.WidthRequest = 74;
		this.labInfo.Name = "labInfo";
		this.labInfo.Xalign = 1F;
		this.labInfo.LabelProp = global::Mono.Unix.Catalog.GetString ("LoginSite:");
		this.hbox1.Add (this.labInfo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.labInfo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(1));
		// Container child hbox1.Gtk.Box+BoxChild
		this.combSites = global::Gtk.ComboBox.NewText ();
		this.combSites.Name = "combSites";
		this.hbox1.Add (this.combSites);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.combSites]));
		w2.Position = 1;
		w2.Padding = ((uint)(9));
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.labUserName = new global::Gtk.Label ();
		this.labUserName.WidthRequest = 75;
		this.labUserName.Name = "labUserName";
		this.labUserName.Xalign = 1F;
		this.labUserName.LabelProp = global::Mono.Unix.Catalog.GetString ("UserName:");
		this.hbox2.Add (this.labUserName);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labUserName]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtUserName = new global::Gtk.Entry ();
		this.txtUserName.CanFocus = true;
		this.txtUserName.Name = "txtUserName";
		this.txtUserName.IsEditable = true;
		this.txtUserName.InvisibleChar = '●';
		this.hbox2.Add (this.txtUserName);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtUserName]));
		w5.Position = 1;
		w5.Padding = ((uint)(8));
		this.vbox2.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.labPassword = new global::Gtk.Label ();
		this.labPassword.WidthRequest = 75;
		this.labPassword.Name = "labPassword";
		this.labPassword.Xalign = 1F;
		this.labPassword.LabelProp = global::Mono.Unix.Catalog.GetString ("   Pssword:");
		this.hbox3.Add (this.labPassword);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labPassword]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.txtPassword = new global::Gtk.Entry ();
		this.txtPassword.CanFocus = true;
		this.txtPassword.Name = "txtPassword";
		this.txtPassword.IsEditable = true;
		this.txtPassword.Visibility = false;
		this.txtPassword.InvisibleChar = '●';
		this.hbox3.Add (this.txtPassword);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.txtPassword]));
		w8.Position = 1;
		w8.Padding = ((uint)(8));
		this.vbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
		this.alignment1.Name = "alignment1";
		// Container child alignment1.Gtk.Container+ContainerChild
		this.labFull = new global::Gtk.Label ();
		this.labFull.WidthRequest = 77;
		this.labFull.Name = "labFull";
		this.labFull.Xalign = 1F;
		this.alignment1.Add (this.labFull);
		this.hbox4.Add (this.alignment1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnLogin = new global::Gtk.Button ();
		this.btnLogin.WidthRequest = 70;
		this.btnLogin.CanFocus = true;
		this.btnLogin.Name = "btnLogin";
		this.btnLogin.UseUnderline = true;
		this.btnLogin.Label = global::Mono.Unix.Catalog.GetString ("Login");
		this.hbox4.Add (this.btnLogin);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnLogin]));
		w12.Position = 1;
		w12.Expand = false;
		w12.Fill = false;
		w12.Padding = ((uint)(8));
		// Container child hbox4.Gtk.Box+BoxChild
		this.btnReset = new global::Gtk.Button ();
		this.btnReset.WidthRequest = 70;
		this.btnReset.CanFocus = true;
		this.btnReset.Name = "btnReset";
		this.btnReset.UseUnderline = true;
		this.btnReset.Label = global::Mono.Unix.Catalog.GetString ("Reset");
		this.hbox4.Add (this.btnReset);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnReset]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		w13.Padding = ((uint)(5));
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		this.vbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vbox2]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.GtkScrolledWindow.BorderWidth = ((uint)(8));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtResult = new global::Gtk.TextView ();
		this.txtResult.CanFocus = true;
		this.txtResult.Name = "txtResult";
		this.txtResult.WrapMode = ((global::Gtk.WrapMode)(1));
		this.GtkScrolledWindow.Add (this.txtResult);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w17.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 347;
		this.DefaultHeight = 328;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnLogin.Clicked += new global::System.EventHandler (this.OnBtnLoginClicked);
		this.btnReset.Clicked += new global::System.EventHandler (this.OnBtnResetClicked);
	}
}
