/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace ImitateLogin
{

  [Serializable]
  public partial class Config : TBase
  {
    private List<Extension> _Extensions;

    public List<Extension> Extensions
    {
      get
      {
        return _Extensions;
      }
      set
      {
        __isset.Extensions = true;
        this._Extensions = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool Extensions;
    }

    public Config() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                Extensions = new List<Extension>();
                TList _list9 = iprot.ReadListBegin();
                for( int _i10 = 0; _i10 < _list9.Count; ++_i10)
                {
                  Extension _elem11 = new Extension();
                  _elem11 = new Extension();
                  _elem11.Read(iprot);
                  Extensions.Add(_elem11);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Config");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Extensions != null && __isset.Extensions) {
        field.Name = "Extensions";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Extensions.Count));
          foreach (Extension _iter12 in Extensions)
          {
            _iter12.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Config(");
      sb.Append("Extensions: ");
      sb.Append(Extensions);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
