/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImitateLogin
{
  public enum LoginSite
  {
    Weibo = 1,
    WeiboWap = 2,
    Taobao = 3,
    QQ = 4,
    Baidu = 5,
    Facebook = 21,
    Twitter = 22,
    Google = 23,
  }
}
