/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImitateLogin
{
  public enum PluginType
  {
    MEF = 1,
    REST = 2,
    Thrift = 3,
  }
}
