/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace ImitateLogin
{
  public enum ResultType
  {
    Success = 200,
    Failed = 400,
    NeedCaptcha = 401,
    UserNameWrong = 402,
    PasswordWrong = 403,
    IpLimit = 404,
    AccounntLimit = 405,
    Timeout = 408,
    ServiceError = 500,
  }
}
